// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
using GameLib.Plugin.BattleNet.Model;

[global::ProtoBuf.ProtoContract()]
internal partial class ProductInstall : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"uid")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Uid { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string productCode { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"settings")]
    public UserSettings Settings { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public CachedProductState cachedProductState { get; set; }

    [global::ProtoBuf.ProtoMember(5)]
    public ProductOperations productOperations { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"keyword")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Keyword { get; set; } = "";
}

[global::ProtoBuf.ProtoContract()]
internal partial class UserSettings : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string installPath { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playRegion { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3)]
    public ShortcutOption desktopShortcut { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public ShortcutOption startmenuShortcut { get; set; }

    [global::ProtoBuf.ProtoMember(5)]
    public LanguageSettingType languageSettings { get; set; }

    [global::ProtoBuf.ProtoMember(6)]
    [global::System.ComponentModel.DefaultValue("")]
    public string selectedTextLanguage { get; set; } = "";

    [global::ProtoBuf.ProtoMember(7)]
    [global::System.ComponentModel.DefaultValue("")]
    public string selectedSpeechLanguage { get; set; } = "";

    [global::ProtoBuf.ProtoMember(8, Name = @"languages")]
    public global::System.Collections.Generic.List<LanguageSetting> Languages { get; } = new global::System.Collections.Generic.List<LanguageSetting>();

    [global::ProtoBuf.ProtoMember(9)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gfxOverrideTags { get; set; } = "";

    [global::ProtoBuf.ProtoMember(10, Name = @"versionbranch")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Versionbranch { get; set; } = "";

    [global::ProtoBuf.ProtoMember(11)]
    [global::System.ComponentModel.DefaultValue("")]
    public string countryCode3Letter { get; set; } = "";

    [global::ProtoBuf.ProtoMember(12)]
    [global::System.ComponentModel.DefaultValue("")]
    public string countryCode2Letter { get; set; } = "";

    [global::ProtoBuf.ProtoMember(13)]
    [global::System.ComponentModel.DefaultValue("")]
    public string productExtra { get; set; } = "";

    [global::ProtoBuf.ProtoContract()]
    public enum ShortcutOption
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SHORTCUT_NONE")]
        ShortcutNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SHORTCUT_USER")]
        ShortcutUser = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"SHORTCUT_ALL_USERS")]
        ShortcutAllUsers = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum LanguageSettingType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"LANGSETTING_NONE")]
        LangsettingNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGSETING_SINGLE")]
        LangsetingSingle = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGSETTING_SIMPLE")]
        LangsettingSimple = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGSETTING_ADVANCED")]
        LangsettingAdvanced = 3,
    }

}

[global::ProtoBuf.ProtoContract()]
internal partial class LanguageSetting : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"language")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Language { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"option")]
    public LanguageOption Option { get; set; }

    [global::ProtoBuf.ProtoContract()]
    public enum LanguageOption
    {
        [global::ProtoBuf.ProtoEnum(Name = @"LANGOPTION_NONE")]
        LangoptionNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGOPTION_TEXT")]
        LangoptionText = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGOPTION_SPEECH")]
        LangoptionSpeech = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGOPTION_TEXT_AND_SPEECH")]
        LangoptionTextAndSpeech = 3,
    }

}

[global::ProtoBuf.ProtoContract()]
internal partial class CachedProductState : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public BaseProductState baseProductState { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public BackfillProgress backfillProgress { get; set; }

    [global::ProtoBuf.ProtoMember(3)]
    public RepairProgress repairProgress { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public UpdateProgress updateProgress { get; set; }

}

[global::ProtoBuf.ProtoContract()]
internal partial class BaseProductState : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"installed")]
    public bool Installed { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"playable")]
    public bool Playable { get; set; }

    [global::ProtoBuf.ProtoMember(3)]
    public bool updateComplete { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public bool backgroundDownloadAvailable { get; set; }

    [global::ProtoBuf.ProtoMember(5)]
    public bool backgroundDownloadComplete { get; set; }

    [global::ProtoBuf.ProtoMember(6)]
    [global::System.ComponentModel.DefaultValue("")]
    public string currentVersion { get; set; } = "";

    [global::ProtoBuf.ProtoMember(7)]
    [global::System.ComponentModel.DefaultValue("")]
    public string currentVersionStr { get; set; } = "";

    [global::ProtoBuf.ProtoMember(8, Name = @"installedBuildConfig")]
    public global::System.Collections.Generic.List<BuildConfig> installedBuildConfigs { get; } = new global::System.Collections.Generic.List<BuildConfig>();

    [global::ProtoBuf.ProtoMember(9, Name = @"backgroundDownloadBuildConfig")]
    public global::System.Collections.Generic.List<BuildConfig> backgroundDownloadBuildConfigs { get; } = new global::System.Collections.Generic.List<BuildConfig>();

    [global::ProtoBuf.ProtoMember(10)]
    [global::System.ComponentModel.DefaultValue("")]
    public string decryptionKey { get; set; } = "";

    [global::ProtoBuf.ProtoMember(11)]
    public global::System.Collections.Generic.List<string> completedInstallActions { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(17, Name = @"tags")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Tags { get; set; } = "";

}

[global::ProtoBuf.ProtoContract()]
internal partial class BuildConfig : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"region")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Region { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string buildConfig { get; set; } = "";

}

[global::ProtoBuf.ProtoContract()]
internal partial class BackfillProgress : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"progress")]
    public double Progress { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"backgrounddownload")]
    public bool Backgrounddownload { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"paused")]
    public bool Paused { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public bool downloadLimit { get; set; }

}

[global::ProtoBuf.ProtoContract()]
internal partial class RepairProgress : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"progress")]
    public double Progress { get; set; }

}

[global::ProtoBuf.ProtoContract()]
internal partial class UpdateProgress : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string lastDiscSetUsed { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"progress")]
    public double Progress { get; set; }

    [global::ProtoBuf.ProtoMember(3)]
    public bool discIgnored { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public ulong totalToDownload { get; set; }

}

[global::ProtoBuf.ProtoContract()]
internal partial class ProductOperations : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public Operation activeOperation { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"priority")]
    public ulong Priority { get; set; }

    [global::ProtoBuf.ProtoContract()]
    public enum Operation
    {
        [global::ProtoBuf.ProtoEnum(Name = @"OP_UPDATE")]
        OpUpdate = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"OP_BACKFILL")]
        OpBackfill = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"OP_REPAIR")]
        OpRepair = 2,
    }

}

[global::ProtoBuf.ProtoContract()]
internal partial class ProductConfig : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string productCode { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string metadataHash { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"timestamp")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Timestamp { get; set; } = "";

}

[global::ProtoBuf.ProtoContract()]
internal partial class ActiveProcess : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string processName { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"pid")]
    public int Pid { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"uri")]
    public global::System.Collections.Generic.List<string> Uris { get; } = new global::System.Collections.Generic.List<string>();

}

[global::ProtoBuf.ProtoContract()]
internal partial class InstallHandshake : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"product")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Product { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"uid")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Uid { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"settings")]
    public UserSettings Settings { get; set; }

}

[global::ProtoBuf.ProtoContract()]
internal partial class DownloadSettings : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public int downloadLimit { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public int backfillLimit { get; set; }

}

[global::ProtoBuf.ProtoContract()]
internal partial class Database : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"productInstall")]
    public global::System.Collections.Generic.List<ProductInstall> productInstalls { get; } = new global::System.Collections.Generic.List<ProductInstall>();

    [global::ProtoBuf.ProtoMember(2)]
    public global::System.Collections.Generic.List<InstallHandshake> activeInstalls { get; } = new global::System.Collections.Generic.List<InstallHandshake>();

    [global::ProtoBuf.ProtoMember(3)]
    public global::System.Collections.Generic.List<ActiveProcess> activeProcesses { get; } = new global::System.Collections.Generic.List<ActiveProcess>();

    [global::ProtoBuf.ProtoMember(4)]
    public global::System.Collections.Generic.List<ProductConfig> productConfigs { get; } = new global::System.Collections.Generic.List<ProductConfig>();

    [global::ProtoBuf.ProtoMember(5)]
    public DownloadSettings downloadSettings { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion


/*
Source: https://www.autohotkey.com/boards/viewtopic.php?f=83&t=84086

syntax = "proto3";

message ProductInstall {
    string uid = 1;
    string productCode = 2;
    UserSettings settings = 3;
    CachedProductState cachedProductState = 4;
    ProductOperations productOperations = 5;
    string keyword = 6;
}

message UserSettings {
    enum ShortcutOption {
        SHORTCUT_NONE = 0;
        SHORTCUT_USER = 1;
        SHORTCUT_ALL_USERS = 2;
    }

    enum LanguageSettingType {
        LANGSETTING_NONE = 0;
        LANGSETING_SINGLE = 1;
        LANGSETTING_SIMPLE = 2;
        LANGSETTING_ADVANCED = 3;
    }

    string installPath = 1;
    string playRegion = 2;
    ShortcutOption desktopShortcut = 3;
    ShortcutOption startmenuShortcut = 4;
    LanguageSettingType languageSettings = 5;
    string selectedTextLanguage = 6;
    string selectedSpeechLanguage = 7;
    repeated LanguageSetting languages = 8;
    string gfxOverrideTags = 9;
    string versionbranch = 10;
    string countryCode3Letter = 11;
    string countryCode2Letter = 12;
    string productExtra = 13;
}

message LanguageSetting {
    enum LanguageOption {
        LANGOPTION_NONE = 0;
        LANGOPTION_TEXT = 1;
        LANGOPTION_SPEECH = 2;
        LANGOPTION_TEXT_AND_SPEECH = 3;
    }

    string language = 1;
    LanguageOption option = 2;
}

message CachedProductState {
    BaseProductState baseProductState = 1;
    BackfillProgress backfillProgress = 2;
    RepairProgress repairProgress = 3;
    UpdateProgress updateProgress = 4;
}

message BaseProductState {
    bool installed = 1;
    bool playable = 2;
    bool updateComplete = 3;
    bool backgroundDownloadAvailable = 4;
    bool backgroundDownloadComplete = 5;
    string currentVersion = 6;
    string currentVersionStr = 7;
    repeated BuildConfig installedBuildConfig = 8;
    repeated BuildConfig backgroundDownloadBuildConfig = 9;
    string decryptionKey = 10;
    repeated string completedInstallActions = 11;
    string tags = 17;
}

message BuildConfig {
    string region = 1;
    string buildConfig = 2;
}

message BackfillProgress {
    double progress = 1;
    bool backgrounddownload = 2;
    bool paused = 3;
    bool downloadLimit = 4;
}

message RepairProgress {
    double progress = 1;
}

message UpdateProgress {
    string lastDiscSetUsed = 1;
    double progress = 2;
    bool discIgnored = 3;
    uint64 totalToDownload = 4;
}

message ProductOperations {
    enum Operation {
        OP_UPDATE = 0;
        OP_BACKFILL = 1;
        OP_REPAIR = 2;
    }

    Operation activeOperation = 1;
    uint64 priority = 2;
}

message ProductConfig {
    string productCode = 1;
    string metadataHash = 2;
    string timestamp = 3;
}

message ActiveProcess {
    string processName = 1;
    int32 pid = 2;
    repeated string uri = 3;
}

message InstallHandshake {
    string product = 1;
    string uid = 2;
    UserSettings settings = 3;
}

message DownloadSettings {
    int32 downloadLimit = 1;
    int32 backfillLimit = 2;
}

message Database {
    repeated ProductInstall productInstall = 1;
    repeated InstallHandshake activeInstalls = 2;
    repeated ActiveProcess activeProcesses = 3;
    repeated ProductConfig productConfigs = 4;
    DownloadSettings downloadSettings = 5;
}
*/